name: echo_verse
description: "The universe of connections and memories"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.6.0


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  responsive_sizer: ^3.3.1
  go_router: ^14.6.3
  equatable: ^2.0.7
  objectbox: ^4.0.3
  objectbox_flutter_libs: ^4.0.3
  path: ^1.9.0
  path_provider: ^2.1.5
  firebase_core: ^3.10.0
  firebase_auth: ^5.4.0
  cloud_firestore: ^5.6.3
  flutter_bloc: ^9.0.0
  bloc: ^9.0.0
  meta: ^1.15.0
  get_it: ^8.0.3
  internet_connection_checker_plus: ^2.7.0
  awesome_snackbar_content: ^0.1.5
  flutter_svg: ^2.0.17
  intl: ^0.19.0
  image_picker: ^1.1.2
  firebase_storage: ^12.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0
  objectbox_generator: ^4.0.3
  build_runner: ^2.4.14

flutter:

  uses-material-design: true

 
  assets:
    - lib/assets/logo/
    - lib/assets/icons/

  fonts:
    - family: OpenSans
      fonts:
        - asset: lib/assets/fonts/Open_Sans/static/OpenSans-Light.ttf
          weight: 300
        - asset: lib/assets/fonts/Open_Sans/static/OpenSans-Regular.ttf
          weight: 400
        - asset: lib/assets/fonts/Open_Sans/static/OpenSans-Medium.ttf
          weight: 500
        - asset: lib/assets/fonts/Open_Sans/static/OpenSans-SemiBold.ttf
          weight: 600
        - asset: lib/assets/fonts/Open_Sans/static/OpenSans-Bold.ttf
          weight: 700

