// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxpHanMtXiC89WckFZW9mmU9gKaTzyWX8',
    appId: '1:507410400542:web:1b01fed014fcd516f5350f',
    messagingSenderId: '507410400542',
    projectId: 'echo-verse05',
    authDomain: 'echo-verse05.firebaseapp.com',
    storageBucket: 'echo-verse05.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8tAnPZ4x_g7elnHjbQGYfg2hlDFEsjTs',
    appId: '1:507410400542:android:fede0e24ef2a7da3f5350f',
    messagingSenderId: '507410400542',
    projectId: 'echo-verse05',
    storageBucket: 'echo-verse05.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOVpobsf91A1A86ac-cKY90zChy3WzDA8',
    appId: '1:507410400542:ios:06d8a0d5ef42cfd5f5350f',
    messagingSenderId: '507410400542',
    projectId: 'echo-verse05',
    storageBucket: 'echo-verse05.firebasestorage.app',
    iosBundleId: 'com.example.echoVerse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOVpobsf91A1A86ac-cKY90zChy3WzDA8',
    appId: '1:507410400542:ios:06d8a0d5ef42cfd5f5350f',
    messagingSenderId: '507410400542',
    projectId: 'echo-verse05',
    storageBucket: 'echo-verse05.firebasestorage.app',
    iosBundleId: 'com.example.echoVerse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxpHanMtXiC89WckFZW9mmU9gKaTzyWX8',
    appId: '1:507410400542:web:99ba041573b7ef6ef5350f',
    messagingSenderId: '507410400542',
    projectId: 'echo-verse05',
    authDomain: 'echo-verse05.firebaseapp.com',
    storageBucket: 'echo-verse05.firebasestorage.app',
  );
}
